package alfi.compitest;

/*Generated by MPS */

import wrappers.javaWrappers.BasicInputOutput;
import wrappers.javaWrappers.IntegerFunctions;

/**
 * foo
 */
public class ActivityForStatementTest {
  public static void ForStatementTest() {
    // print 5,6,7,8,9
    for (int i = 5; i <= 9; i++) {
      BasicInputOutput.WriteLine(IntegerFunctions.ToString(i));
    }
  }
  public static void main(String[] args) {
    ForStatementTest();
  }
}
