package alfi.compitest;

/*Generated by MPS */

import wrappers.javaWrappers.BasicInputOutput;
import wrappers.javaWrappers.BooleanFunctions;
import wrappers.javaWrappers.IntegerFunctions;

/**
 * foo
 */
public class ActivityUnaryExpressionsTest {
  public static void UnaryExpressionsTest() {
    // Boolean

    Boolean b = false;
    BasicInputOutput.WriteLine(BooleanFunctions.ToString(!(b)));

    // BitString

    Integer i = 123;
    BasicInputOutput.WriteLine(IntegerFunctions.ToString((Integer) ~(i)));

    // Numeric

    BasicInputOutput.WriteLine(IntegerFunctions.ToString(i));
    BasicInputOutput.WriteLine(IntegerFunctions.ToString(-i));
  }
  public static void main(String[] args) {
    UnaryExpressionsTest();
  }
}
