package alfi.compitest;

/*Generated by MPS */

import wrappers.javaWrappers.BasicInputOutput;

/**
 * foo
 */
public class ActivityIfStatementTest {
  public static void IfStatementTest() {
    if (false) {
      BasicInputOutput.WriteLine("ignored");
    }

    if (true) {
      BasicInputOutput.WriteLine("a1");
    } else if (true) {
      BasicInputOutput.WriteLine("a2");
    } else if (true) {
      BasicInputOutput.WriteLine("a3");
    } else if (true) {
      BasicInputOutput.WriteLine("a4");
    } else {
      BasicInputOutput.WriteLine("a5");
    }

    if (false) {
      BasicInputOutput.WriteLine("b1");
    } else if (true) {
      BasicInputOutput.WriteLine("b2");
    } else if (true) {
      BasicInputOutput.WriteLine("b3");
    } else if (true) {
      BasicInputOutput.WriteLine("b4");
    } else {
      BasicInputOutput.WriteLine("b5");
    }

    if (false) {
      BasicInputOutput.WriteLine("c1");
    } else if (false) {
      BasicInputOutput.WriteLine("c2");
    } else if (true) {
      BasicInputOutput.WriteLine("c3");
    } else if (true) {
      BasicInputOutput.WriteLine("c4");
    } else {
      BasicInputOutput.WriteLine("c5");
    }
    if (false) {
      BasicInputOutput.WriteLine("d1");
    } else if (false) {
      BasicInputOutput.WriteLine("d2");
    } else if (false) {
      BasicInputOutput.WriteLine("d3");
    } else if (true) {
      BasicInputOutput.WriteLine("d4");
    } else {
      BasicInputOutput.WriteLine("d5");
    }

    if (false) {
      BasicInputOutput.WriteLine("e1");
    } else if (false) {
      BasicInputOutput.WriteLine("e2");
    } else if (false) {
      BasicInputOutput.WriteLine("e3");
    } else if (false) {
      BasicInputOutput.WriteLine("e4");
    } else {
      BasicInputOutput.WriteLine("e5");
    }
  }
  public static void main(String[] args) {
    IfStatementTest();
  }
}
