package alfi.compitest;

/*Generated by MPS */

import wrappers.javaWrappers.BasicInputOutput;
import wrappers.javaWrappers.IntegerFunctions;

/**
 * foo
 */
public class ActivityBreakStatementTest {
  public static void BreakStatementTest() {
    Integer a = 0;
    while (true) {
      a = a + 1;
      BasicInputOutput.WriteLine(IntegerFunctions.ToString(a));
      if (a > 10) {
        break;
      }
    }
    BasicInputOutput.WriteLine("End: " + IntegerFunctions.ToString(a));

  }
  public static void main(String[] args) {
    BreakStatementTest();
  }
}
