package alfi.compitest;

/*Generated by MPS */

import wrappers.javaWrappers.BasicInputOutput;
import wrappers.javaWrappers.BooleanFunctions;
import wrappers.javaWrappers.IntegerFunctions;
import java.util.Objects;

/**
 * foo
 */
public class ActivityLiteralExpressionsTest {
  public static void LiteralExpressionsTest() {
    String a = "Test";
    BasicInputOutput.WriteLine(a);
    Boolean b = false;
    BasicInputOutput.WriteLine(BooleanFunctions.ToString(b));
    Boolean c = true;
    BasicInputOutput.WriteLine(BooleanFunctions.ToString(c));
    Integer d = 12309;
    BasicInputOutput.WriteLine(IntegerFunctions.ToString(d));
    Integer e = 0b10111;
    BasicInputOutput.WriteLine(IntegerFunctions.ToString(e));
    Integer f = 0xA09F;
    BasicInputOutput.WriteLine(IntegerFunctions.ToString(f));
    Integer g = 012307;
    BasicInputOutput.WriteLine(IntegerFunctions.ToString(g));

    String emptyString = "";
    if (Objects.equals(emptyString, "")) {
      BasicInputOutput.WriteLine("empty");
    }

    BasicInputOutput.WriteLine("Line1\nLine2\nLine3");
    if (Objects.equals("a\"=\\\nb", "a\"=\\\nb")) {
      BasicInputOutput.WriteLine("multiline equals");
    }
  }
  public static void main(String[] args) {
    LiteralExpressionsTest();
  }
}
