package alfi.compitest;

/*Generated by MPS */

import wrappers.javaWrappers.BasicInputOutput;

/**
 * foo
 */
public class ActivityWhileStatementTest {
  public static void WhileStatementTest() {
    Integer a = 0;
    while (a < 10) {
      a = a + 1;
      BasicInputOutput.WriteLine(Integer.toString(a));
    }
    BasicInputOutput.WriteLine("End: " + Integer.toString(a));
  }
  public static void main(String[] args) {
    WhileStatementTest();
  }
}
