package alfi.compitest;

/*Generated by MPS */

import wrappers.javaWrappers.BasicInputOutput;
import java.util.Objects;

/**
 * foo
 */
public class ActivityEnumTest {
  public static void EnumTest() {
    EnumTrafficLightColor enumValue = EnumTrafficLightColor.GREEN;

    BasicInputOutput.WriteLine(EnumTrafficLightColorToString.EnumTrafficLightColorToString(EnumTrafficLightColor.GREEN));

    if (Objects.equals(enumValue, EnumTrafficLightColor.GREEN)) {
      BasicInputOutput.WriteLine("GREEN!");
    }
    enumValue = EnumTrafficLightColor.RED;

    if (Objects.equals(enumValue, EnumTrafficLightColor.GREEN)) {
      BasicInputOutput.WriteLine("GREEN!");
    } else if (Objects.equals(enumValue, EnumTrafficLightColor.RED)) {
      BasicInputOutput.WriteLine("RED!");
    }
  }
  public static void main(String[] args) {
    EnumTest();
  }
}
