package alfi.compitest;

/*Generated by MPS */

import alfi.compitest.Sequences.SequenceHolder;
import wrappers.javaWrappers.BasicInputOutput;
import wrappers.javaWrappers.IntegerFunctions;
import java.util.Iterator;
import alfi.compitest.Sequences.SeqRow;
import java.util.List;
import wrappers.javaWrappers.BooleanFunctions;
import java.util.ArrayList;
import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.LinkedHashMap;
import java.util.Set;
import java.util.LinkedHashSet;

/**
 * foo
 */
public class ActivitySequencesTest {
  public static void SequencesTest() {
    SequenceHolder sequenceHolder = new SequenceHolder();

    sequenceHolder.names.add("Test1");
    sequenceHolder.names.add("Test2");
    sequenceHolder.names.add("Test3");
    BasicInputOutput.WriteLine(IntegerFunctions.ToString(sequenceHolder.names.size()));

    {
      // was a for loop
      Iterator<String> forLoop_shvzm_h0a_mainIterator = sequenceHolder.names.iterator();
      while (forLoop_shvzm_h0a_mainIterator.hasNext()) {
        String name = forLoop_shvzm_h0a_mainIterator.next();

        BasicInputOutput.WriteLine(name);
      }
    }

    sequenceHolder.names.remove("Test2");
    sequenceHolder.names.remove(1 - 1);

    {
      // was a for loop
      Iterator<String> forLoop_shvzm_m0a_mainIterator = sequenceHolder.names.iterator();
      while (forLoop_shvzm_m0a_mainIterator.hasNext()) {
        String name = forLoop_shvzm_m0a_mainIterator.next();

        BasicInputOutput.WriteLine(name);
      }
    }

    SeqRow row1 = new SeqRow(false);
    sequenceHolder.rows.add(row1);
    row1.values.add("val1");
    row1.values.add("val2");
    SeqRow helperVar_shvzm_s0a_1 = sequenceHolder.rows.get(1 - 1);
    List<String> helperVar_shvzm_s0a_0 = helperVar_shvzm_s0a_1.values;
    String helperVar_shvzm_s0a = helperVar_shvzm_s0a_0.get(1 - 1);
    BasicInputOutput.WriteLine((helperVar_shvzm_s0a != null ? helperVar_shvzm_s0a : "null"));

    // Nested null-propagation-access
    if (true) {
      if (true) {
        SeqRow helperVar_shvzm_a0a0a0a0w0a = sequenceHolder.rows.get(1 - 1);
        Boolean helperVar_shvzm_a0a0a0a0v0a = helperVar_shvzm_a0a0a0a0w0a.marked;
        BasicInputOutput.WriteLine(BooleanFunctions.ToString((helperVar_shvzm_a0a0a0a0v0a != null ? helperVar_shvzm_a0a0a0a0v0a : false)));
      }
    }

    SeqRow rowAt1 = sequenceHolder.rows.get(1 - 1);
    Boolean helperVar_shvzm_y0a = rowAt1.marked;
    BasicInputOutput.WriteLine(BooleanFunctions.ToString((helperVar_shvzm_y0a != null ? helperVar_shvzm_y0a : false)));
    sequenceHolder.markAt(1);
    Boolean helperVar_shvzm_ab0a = rowAt1.marked;
    BasicInputOutput.WriteLine(BooleanFunctions.ToString((helperVar_shvzm_ab0a != null ? helperVar_shvzm_ab0a : false)));

    List<Integer> integers = new ArrayList<>();
    integers.add(1);
    integers.add(2);
    integers.add(3);
    {
      // was a for loop
      Iterator<Integer> forLoop_shvzm_lb0a_mainIterator = integers.iterator();
      while (forLoop_shvzm_lb0a_mainIterator.hasNext()) {
        Integer number = forLoop_shvzm_lb0a_mainIterator.next();

        BasicInputOutput.WriteLine(IntegerFunctions.ToString(number));
      }
    }

    Integer firstInt = integers.get(1 - 1);
    if (!(Objects.equals(firstInt, null))) {
      if (firstInt > 0) {
        BasicInputOutput.WriteLine(IntegerFunctions.ToString((firstInt != null ? firstInt : -1)));
      }
    }

    // test assigment with rhs is Optional
    SeqRow newRow = new SeqRow(false);
    SeqRow helperVar_shvzm_nb0a = sequenceHolder.rows.get(1 - 1);
    Boolean row1Marked = helperVar_shvzm_nb0a.marked;
    if (!(Objects.equals(row1Marked, null))) {
      // lhs is not Optional
      newRow.marked = row1Marked;
      // lhs is Optional
      rowAt1.marked = row1Marked;
    }
    Boolean helperVar_shvzm_tb0a = rowAt1.IsMarkedEqual(newRow);
    if (Objects.equals(helperVar_shvzm_tb0a, true)) {
      BasicInputOutput.WriteLine("IsMarkedEqual==true");
    }
    // lhs is object variable, rhs is Optional PropertyAccess
    SeqRow optionalRow = null;
    optionalRow = sequenceHolder.optionalSpecialRow;

    // test optional boolean as if argument
    if (!(Objects.equals(rowAt1, null))) {
      rowAt1.marked = false;
      Boolean helperVar_shvzm_b0a0zb0a = rowAt1.marked;
      if (Objects.equals(helperVar_shvzm_b0a0zb0a, true)) {
        BasicInputOutput.WriteLine("Marked!");
      } else {
        BasicInputOutput.WriteLine("Unmarked!");
      }
      rowAt1.marked = true;
      Boolean helperVar_shvzm_d0a0zb0a = rowAt1.marked;
      if (Objects.equals(helperVar_shvzm_d0a0zb0a, true)) {
        BasicInputOutput.WriteLine("Marked!");
      } else {
        BasicInputOutput.WriteLine("Unmarked!");
      }
    }
    // test calling operation on optional object
    if (!(Objects.equals(optionalRow, null))) {
      optionalRow.RowOperation();
    }

    // sequence creation expression
    sequenceHolder.setNames(Arrays.asList("A", "B"));
    {
      // was a for loop
      Iterator<String> forLoop_shvzm_ic0a_mainIterator = sequenceHolder.names.iterator();
      while (forLoop_shvzm_ic0a_mainIterator.hasNext()) {
        String name = forLoop_shvzm_ic0a_mainIterator.next();

        BasicInputOutput.WriteLine(name);
      }
    }
    List<String> emptySequence = Arrays.asList();
    if (emptySequence.isEmpty()) {
      BasicInputOutput.WriteLine("emptySequence2: is empty");
    }

    // sequence access expression
    String helperVar_shvzm_kc0a = sequenceHolder.names.get(1 - 1);
    BasicInputOutput.WriteLine((helperVar_shvzm_kc0a != null ? helperVar_shvzm_kc0a : "null"));
    BasicInputOutput.WriteLine(sequenceHolder.names.get(1 - 1));

    // inference test
    List<String> namesInferred = sequenceHolder.names;
    {
      // was a for loop
      Iterator<String> forLoop_shvzm_tc0a_mainIterator = namesInferred.iterator();
      while (forLoop_shvzm_tc0a_mainIterator.hasNext()) {
        String name = forLoop_shvzm_tc0a_mainIterator.next();

        BasicInputOutput.WriteLine(name);
      }
    }

    // map/set creation collections
    // note: methods like add, get, includes, etc. are not supported yet
    Map<String, String> myMap = new LinkedHashMap<>();
    Set<Integer> mySet = new LinkedHashSet<>();
  }
  public static void main(String[] args) {
    SequencesTest();
  }
}
