package alfi.compitest;

/*Generated by MPS */

import wrappers.javaWrappers.BasicInputOutput;

/**
 * foo
 */
public class ActivityForStatementTest {
  public static void ForStatementTest() {
    // print 5,6,7,8,9
    for (int i = 5; i <= 9; i++) {
      BasicInputOutput.WriteLine(Integer.toString(i));
    }
  }
  public static void main(String[] args) {
    ForStatementTest();
  }
}
