package alfi.compitest;

/*Generated by MPS */

import wrappers.javaWrappers.BasicInputOutput;
import wrappers.javaWrappers.IntegerFunctions;
import wrappers.javaWrappers.BooleanFunctions;
import java.util.Objects;

/**
 * foo
 */
public class ActivityBinaryExpressionsTest {
  public static void BinaryExpressionsTest() {
    // Arithmetic Expressions

    BasicInputOutput.WriteLine(IntegerFunctions.ToString(12 + 45));
    BasicInputOutput.WriteLine(IntegerFunctions.ToString(12 - 45));
    BasicInputOutput.WriteLine(IntegerFunctions.ToString(12 * 45));
    BasicInputOutput.WriteLine(IntegerFunctions.ToString(121 % 5));

    // Shift Expressions

    BasicInputOutput.WriteLine(IntegerFunctions.ToString((Integer) (121 << 2)));
    BasicInputOutput.WriteLine(IntegerFunctions.ToString((Integer) (121 >> 2)));
    BasicInputOutput.WriteLine(IntegerFunctions.ToString((Integer) (121 >>> 2)));
    BasicInputOutput.WriteLine(IntegerFunctions.ToString((Integer) (-121 >> 2)));
    BasicInputOutput.WriteLine(IntegerFunctions.ToString((Integer) (-121 >>> 2)));

    // Relational Expressions

    BasicInputOutput.WriteLine(BooleanFunctions.ToString(5 < 9));
    BasicInputOutput.WriteLine(BooleanFunctions.ToString(5 < 5));
    BasicInputOutput.WriteLine(BooleanFunctions.ToString(5 < 3));

    BasicInputOutput.WriteLine(BooleanFunctions.ToString(5 <= 9));
    BasicInputOutput.WriteLine(BooleanFunctions.ToString(5 <= 5));
    BasicInputOutput.WriteLine(BooleanFunctions.ToString(5 <= 3));

    BasicInputOutput.WriteLine(BooleanFunctions.ToString(5 > 9));
    BasicInputOutput.WriteLine(BooleanFunctions.ToString(5 > 5));
    BasicInputOutput.WriteLine(BooleanFunctions.ToString(5 > 3));

    BasicInputOutput.WriteLine(BooleanFunctions.ToString(5 >= 9));
    BasicInputOutput.WriteLine(BooleanFunctions.ToString(5 >= 5));
    BasicInputOutput.WriteLine(BooleanFunctions.ToString(5 >= 3));

    // Equality Expressions

    BasicInputOutput.WriteLine(BooleanFunctions.ToString(Objects.equals(1, 1)));
    BasicInputOutput.WriteLine(BooleanFunctions.ToString(Objects.equals(1, 3)));
    BasicInputOutput.WriteLine(BooleanFunctions.ToString(Objects.equals("a", "a")));
    BasicInputOutput.WriteLine(BooleanFunctions.ToString(Objects.equals("a", "ab")));

    BasicInputOutput.WriteLine(BooleanFunctions.ToString(!(Objects.equals(1, 1))));
    BasicInputOutput.WriteLine(BooleanFunctions.ToString(!(Objects.equals(1, 3))));
    BasicInputOutput.WriteLine(BooleanFunctions.ToString(!(Objects.equals("a", "a"))));
    BasicInputOutput.WriteLine(BooleanFunctions.ToString(!(Objects.equals("a", "ab"))));

    // Logical Expression

    BasicInputOutput.WriteLine(BooleanFunctions.ToString(true & true));
    BasicInputOutput.WriteLine(BooleanFunctions.ToString(true & false));
    BasicInputOutput.WriteLine(BooleanFunctions.ToString(false & false));

    BasicInputOutput.WriteLine(BooleanFunctions.ToString(true ^ true));
    BasicInputOutput.WriteLine(BooleanFunctions.ToString(true ^ false));
    BasicInputOutput.WriteLine(BooleanFunctions.ToString(false ^ false));

    BasicInputOutput.WriteLine(BooleanFunctions.ToString(true | true));
    BasicInputOutput.WriteLine(BooleanFunctions.ToString(true | false));
    BasicInputOutput.WriteLine(BooleanFunctions.ToString(false | false));

    // Conditional Expression

    BasicInputOutput.WriteLine(BooleanFunctions.ToString(true && true));
    BasicInputOutput.WriteLine(BooleanFunctions.ToString(true && false));
    BasicInputOutput.WriteLine(BooleanFunctions.ToString(false && false));

    BasicInputOutput.WriteLine(BooleanFunctions.ToString(true || true));
    BasicInputOutput.WriteLine(BooleanFunctions.ToString(true || false));
    BasicInputOutput.WriteLine(BooleanFunctions.ToString(false || false));
  }
  public static void main(String[] args) {
    BinaryExpressionsTest();
  }
}
