package alfi.compitest;

/*Generated by MPS */

import wrappers.javaWrappers.BasicInputOutput;
import wrappers.javaWrappers.IntegerFunctions;

/**
 * foo
 */
public class ActivityDoStatementTest {
  public static void DoStatementTest() {
    Integer a = 0;
    Integer b = 0;
    do {
      b = a * 2;
      a = a + 1;
      BasicInputOutput.WriteLine(IntegerFunctions.ToString(a));
      BasicInputOutput.WriteLine(IntegerFunctions.ToString(b));
    } while (b < 20);

    BasicInputOutput.WriteLine("End: " + IntegerFunctions.ToString(a));
  }
  public static void main(String[] args) {
    DoStatementTest();
  }
}
