package alfi.compitest;

/*Generated by MPS */

import java.util.ArrayList;

/**
 * foo
 */
public class ActivityCollectionsTest {
  public static void CollectionsTest() {
    ArrayList<String> list = new ArrayList<>();
  }
  public static void main(String[] args) {
    CollectionsTest();
  }
}
