package alfi.compitest;

/*Generated by MPS */

import alfi.compitest.Cars.Car;
import wrappers.javaWrappers.BasicInputOutput;
import alfi.compitest.Cars.Vehicle;
import java.util.Objects;

/**
 * foo
 */
public class ActivityCarsTest {
  public static void CarsTest() {
    Car car = new Car();
    car.startEngine();
    BasicInputOutput.WriteLine(Integer.toString(car.distance));
    Vehicle vehicle = car;
    vehicle.drive();
    BasicInputOutput.WriteLine(Integer.toString(vehicle.distance));
    BasicInputOutput.WriteLine(Integer.toString(car.distance));
    car.drive();
    BasicInputOutput.WriteLine(Integer.toString(car.distance));
    BasicInputOutput.WriteLine(car.getColor());
    car.setColor("Red");
    BasicInputOutput.WriteLine(car.getColor());

    // nested classifiers
    Car.Model model = new Car.Model("My Model", Car.ModelKind.Limousine);
    car.model = model;
    BasicInputOutput.WriteLine(car.model.Name);
    if (Objects.equals(model.Kind, Car.ModelKind.Limousine)) {
      BasicInputOutput.WriteLine("Limousine");
    }

    Car.Wheel wheel = new Car.Wheel();
    car.addWheel(wheel);
  }
  public static void main(String[] args) {
    CarsTest();
  }
}
