package alfi.compitest;

/*Generated by MPS */

import wrappers.javaWrappers.BasicInputOutput;
import java.util.Objects;

/**
 * foo
 */
public class ActivityHello {
  public static void Hello() {
    BasicInputOutput.WriteLine("Hello!");
    BasicInputOutput.WriteLine("How are you?");
    String input = BasicInputOutput.ReadLine();

    if (Objects.equals(input, "good")) {
      BasicInputOutput.WriteLine("Ok nice");
    } else {
      BasicInputOutput.WriteLine("Ok");
    }
  }
  public static void main(String[] args) {
    Hello();
  }
}
