package alfi.compitest;

/*Generated by MPS */

import wrappers.javaWrappers.BasicInputOutput;
import wrappers.javaWrappers.IntegerFunctions;

/**
 * foo
 */
public class ActivityWhileStatementTest {
  public static void WhileStatementTest() {
    Integer a = 0;
    while (a < 10) {
      a = a + 1;
      BasicInputOutput.WriteLine(IntegerFunctions.ToString(a));
    }
    BasicInputOutput.WriteLine("End: " + IntegerFunctions.ToString(a));
  }
  public static void main(String[] args) {
    WhileStatementTest();
  }
}
