package alfi.compitest;

/*Generated by MPS */

import wrappers.javaWrappers.BasicInputOutput;

/**
 * foo
 */
public class ActivityHelloWorld {
  public static void HelloWorld() {
    BasicInputOutput.WriteLine("Hello World");
  }
  public static void main(String[] args) {
    HelloWorld();
  }
}
