package alfi.compitest;

/*Generated by MPS */

import wrappers.javaWrappers.BasicInputOutput;

/**
 * foo
 */
public class ActivityUnaryExpressionsTest {
  public static void UnaryExpressionsTest() {
    // Boolean

    Boolean b = false;
    BasicInputOutput.WriteLine(Boolean.toString(!(b)));

    // BitString

    Integer i = 123;
    BasicInputOutput.WriteLine(Integer.toString((Integer) ~(i)));

    // Numeric

    BasicInputOutput.WriteLine(Integer.toString(i));
    BasicInputOutput.WriteLine(Integer.toString(-i));
  }
  public static void main(String[] args) {
    UnaryExpressionsTest();
  }
}
