package alfi.compitest;

/*Generated by MPS */

import wrappers.javaWrappers.BasicInputOutput;
import java.util.Objects;

/**
 * foo
 */
public class ActivityBinaryExpressionsTest {
  public static void BinaryExpressionsTest() {
    // Arithmetic Expressions

    BasicInputOutput.WriteLine(Integer.toString(12 + 45));
    BasicInputOutput.WriteLine(Integer.toString(12 - 45));
    BasicInputOutput.WriteLine(Integer.toString(12 * 45));
    BasicInputOutput.WriteLine(Integer.toString(121 % 5));

    // Shift Expressions

    BasicInputOutput.WriteLine(Integer.toString((Integer) (121 << 2)));
    BasicInputOutput.WriteLine(Integer.toString((Integer) (121 >> 2)));
    BasicInputOutput.WriteLine(Integer.toString((Integer) (121 >>> 2)));
    BasicInputOutput.WriteLine(Integer.toString((Integer) (-121 >> 2)));
    BasicInputOutput.WriteLine(Integer.toString((Integer) (-121 >>> 2)));

    // Relational Expressions

    BasicInputOutput.WriteLine(Boolean.toString(5 < 9));
    BasicInputOutput.WriteLine(Boolean.toString(5 < 5));
    BasicInputOutput.WriteLine(Boolean.toString(5 < 3));

    BasicInputOutput.WriteLine(Boolean.toString(5 <= 9));
    BasicInputOutput.WriteLine(Boolean.toString(5 <= 5));
    BasicInputOutput.WriteLine(Boolean.toString(5 <= 3));

    BasicInputOutput.WriteLine(Boolean.toString(5 > 9));
    BasicInputOutput.WriteLine(Boolean.toString(5 > 5));
    BasicInputOutput.WriteLine(Boolean.toString(5 > 3));

    BasicInputOutput.WriteLine(Boolean.toString(5 >= 9));
    BasicInputOutput.WriteLine(Boolean.toString(5 >= 5));
    BasicInputOutput.WriteLine(Boolean.toString(5 >= 3));

    // Equality Expressions

    BasicInputOutput.WriteLine(Boolean.toString(Objects.equals(1, 1)));
    BasicInputOutput.WriteLine(Boolean.toString(Objects.equals(1, 3)));
    BasicInputOutput.WriteLine(Boolean.toString(Objects.equals("a", "a")));
    BasicInputOutput.WriteLine(Boolean.toString(Objects.equals("a", "ab")));

    BasicInputOutput.WriteLine(Boolean.toString(!(Objects.equals(1, 1))));
    BasicInputOutput.WriteLine(Boolean.toString(!(Objects.equals(1, 3))));
    BasicInputOutput.WriteLine(Boolean.toString(!(Objects.equals("a", "a"))));
    BasicInputOutput.WriteLine(Boolean.toString(!(Objects.equals("a", "ab"))));

    // Logical Expression

    BasicInputOutput.WriteLine(Boolean.toString(true & true));
    BasicInputOutput.WriteLine(Boolean.toString(true & false));
    BasicInputOutput.WriteLine(Boolean.toString(false & false));

    BasicInputOutput.WriteLine(Boolean.toString(true ^ true));
    BasicInputOutput.WriteLine(Boolean.toString(true ^ false));
    BasicInputOutput.WriteLine(Boolean.toString(false ^ false));

    BasicInputOutput.WriteLine(Boolean.toString(true | true));
    BasicInputOutput.WriteLine(Boolean.toString(true | false));
    BasicInputOutput.WriteLine(Boolean.toString(false | false));

    // Conditional Expression

    BasicInputOutput.WriteLine(Boolean.toString(true && true));
    BasicInputOutput.WriteLine(Boolean.toString(true && false));
    BasicInputOutput.WriteLine(Boolean.toString(false && false));

    BasicInputOutput.WriteLine(Boolean.toString(true || true));
    BasicInputOutput.WriteLine(Boolean.toString(true || false));
    BasicInputOutput.WriteLine(Boolean.toString(false || false));

    // Conditional Test Expression

    BasicInputOutput.WriteLine((true ? "val1" : "val2"));
    BasicInputOutput.WriteLine((false ? "val1" : "val2"));
    BasicInputOutput.WriteLine((true ? ((true ? "val1" : "val2")) : ((true ? "val3" : "val4"))));
    BasicInputOutput.WriteLine((false ? ((true ? "val1" : "val2")) : ((true ? "val3" : "val4"))));
  }
  public static void main(String[] args) {
    BinaryExpressionsTest();
  }
}
