package alfi.compitest;

/*Generated by MPS */

import java.util.Objects;

/**
 * foo
 */
public class EnumTrafficLightColorToString {
  public static String EnumTrafficLightColorToString(EnumTrafficLightColor value) {
    if (Objects.equals(value, EnumTrafficLightColor.RED)) {
      return "RED";
    }
    if (Objects.equals(value, EnumTrafficLightColor.GREEN)) {
      return "GREEN";
    }
    if (Objects.equals(value, EnumTrafficLightColor.YELLOW)) {
      return "YELLOW";
    }
    return "?";
  }
}
