package alfi.compitest.Cars;

/*Generated by MPS */

import wrappers.javaWrappers.BasicInputOutput;
import wrappers.javaWrappers.IntegerFunctions;
import java.util.List;
import java.util.LinkedList;

public class Car extends Vehicle implements IHasColor {
  @Override
  public Integer getSpeed() {
    return 10;
  }
  @Override
  public void startEngine() {
    BasicInputOutput.WriteLine("Car engine started");
    BasicInputOutput.WriteLine("Initial speed: " + IntegerFunctions.ToString(this.getSpeed()));

    super.defaultStartEngine();
  }
  @Override
  public String getColor() {
    return this.color;
  }
  public void setColor(String color) {
    this.color = color;
  }
  private String color = "Black";

  public static class Wheel {
    public Integer size = 10;
  }
  public List<Wheel> wheels = new LinkedList<>();
  public void addWheel(Wheel wheel) {
    BasicInputOutput.WriteLine("Adding wheel: " + IntegerFunctions.ToString(wheel.size));
    this.wheels.add(wheel);
  }

  /**
   * foo
   */
  public enum ModelKind {
    PKW(),
    Limousine()
  }
  public static class Model {
    public String Name;
    public ModelKind Kind;
    public Model() {
    }
    public Model(String Name, ModelKind Kind) {
      this.Name = Name;
      this.Kind = Kind;
    }
  }
  public Model model;
}
