package alfi.compitest.Cars;

/*Generated by MPS */

import wrappers.javaWrappers.BasicInputOutput;

public abstract class Vehicle {
  public void drive() {
    this.distance = this.distance + 1;
  }

  protected Integer getSpeed() {
    return 5;
  }
  protected void defaultStartEngine() {
    BasicInputOutput.WriteLine("Vehicle engine started");
  }

  public abstract void startEngine();
  public Integer distance = 0;
}
