package alfi.compitest.Sequences;

/*Generated by MPS */

import java.util.List;
import java.util.LinkedList;
import wrappers.javaWrappers.BasicInputOutput;
import java.util.Objects;

public class SeqRow {
  public SeqRow(Boolean marked) {
    this.marked = marked;
  }

  public List<String> values = new LinkedList<>();
  public Boolean marked;

  public void RowOperation() {
    BasicInputOutput.WriteLine(">> RowOperation");
  }
  public Boolean IsMarkedEqual(SeqRow other) {
    return Objects.equals(this.marked, other.marked);
  }
}
