package alfi.compitest.Sequences;

/*Generated by MPS */

import java.util.List;
import java.util.LinkedList;

public class SequenceHolder {
  public List<String> names = new LinkedList<>();
  public List<SeqRow> rows = new LinkedList<>();
  public List<SeqRow> optionalRows = new LinkedList<>();

  public void markAt(Integer rowIndex) {
    SeqRow helperVar_ekeyye_a0e0 = this.rows.get(rowIndex - 1);
    helperVar_ekeyye_a0e0.marked = true;
  }

  public SeqRow optionalSpecialRow;

  public void setNames(List<String> names) {
    this.names = names;
  }
}
